[package]
name = "srcset"
version = "0.7.16"
edition = "2021"

[dependencies]

argparse = "0.2.2"
image = "0.23.14"
rayon = "1.5"
regex = "1"
lazy_static = "1.4.0"
anyhow = "1.0"

# print stuff
human_bytes = "0.3.0"
yansi = "0.5.0"