[package]
name = "srcset"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


argparse = "0.2.2"
image = "0.23.14"
path-dsl = "0.6.1"
rayon = "1.5"
anyhow = "1.0"
